name: 'Tag Release'

on:
  push:
    branches:
      - main
      - 'release-*'
    paths:
      - version.go

jobs:
  tag-release:
    runs-on: ubuntu-24.04

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - run: /usr/bin/git config --global user.email actions@github.com
      - run: /usr/bin/git config --global user.name 'GitHub Actions Release Tagger'
      - run: hack/tag-release.sh
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - id: image-meta
        run: |
          echo "tag=v$(hack/get-version.sh)" >> "$GITHUB_OUTPUT"
          echo "gitsha=$(git describe --always)" >> "$GITHUB_OUTPUT"
      - id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/arm64,linux/amd64
          tags: norseto/oci-lb-registrar:${{ steps.image-meta.outputs.tag }}
          build-args: |
            MODULE_PACKAGE=github.com/norseto/oci-lb-controller
            GITVERSION=${{ steps.image-meta.outputs.gitsha }}
          provenance: true
          sbom: true
      - uses: sigstore/cosign-installer@v3
      - run: cosign sign --yes norseto/oci-lb-registrar@${{ steps.build.outputs.digest }}
